Update files for tribute page
herokudev/tribute-page pull request #1
Opened 2021-07-07 19:15 UTC by herokudev

Here are the files for the new tribute page

2021-07-07 19:52 UTC, herokudev commented on index.html
> +          <section id="title">
Good semantic HTML tags, use <section> instead of <div>

2021-07-07 19:59 UTC, herokudev reviewed
Great code with no Linter errors, keep the good work!!

2021-07-07 19:59 UTC, herokudev commented on index.html
> +            <article id="tribute" class="text-content">
You could use a header for an article.

2021-07-07 19:59 UTC, herokudev commented on index.html
> +          <section id="title">
Great semantic HTML tags, use the section tag instead of the div tag.

2021-07-08 00:26 UTC, de-scholar requested changes
Hi @herokudev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 00:26 UTC, de-scholar commented on index.html
> +          <section id="title">
- [ ] I suggest you explain why this change is required, that will make it very easy to implement the changes because the one who will read it will know the context

- [ ] And also it would be very nice if your feedback is formatted politely, that will help the student to implement changes with positive mindset

2021-07-08 00:26 UTC, de-scholar commented on index.html
> +            <article id="tribute" class="text-content">
- [ ] I suggest you explain why this change is required, that will make it very easy to implement the changes because the one who will read it will know the context

2021-07-08 15:16 UTC, herokudev reviewed
Hello, I have added some some details of my code review as you asked. Thanks for your help.

2021-07-08 15:16 UTC, herokudev commented on index.html
> +          <section id="title">
I thinks that in the best practices standards it suggests you to use some tags instead of others, I would like to make you the same suggestions so your code would be nicer.

2021-07-08 15:16 UTC, herokudev commented on index.html
> +            <article id="tribute" class="text-content">
I thinks that in the best practices standards it suggests you to use some tags instead of others, I would like to make you the same suggestions so your code would be nicer.

2021-07-08 16:10 UTC, vichuge approved these changes

2021-07-08 16:10 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 16:21 UTC, merged